"""
Build a seed catalog from known SHL Individual Test Solutions.
This is a reliable fallback if scraping fails.
Run: python scripts/build_seed_catalog.py
"""

import json

# Known SHL Individual Test Solutions from public catalog
# Sources: shl.com product catalog, public documentation
SEED_CATALOG = [
    # ── COGNITIVE / ABILITY ──────────────────────────────────────────
    {
        "name": "Verify Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-reasoning-test/",
        "description": "Measures ability to interpret numerical data, graphs, and tables. Suitable for roles requiring data analysis and quantitative decision-making.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "duration": "17 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in 30+ languages"],
        "raw_text": "Numerical reasoning test measuring ability to work with numbers, graphs, charts, and data tables. Used for graduate, managerial, and professional roles. Assesses quantitative analysis, data interpretation.",
    },
    {
        "name": "Verify Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-reasoning-test/",
        "description": "Measures ability to understand written information and draw logical conclusions. Suitable for roles with high communication and comprehension demands.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "duration": "17 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in 30+ languages"],
        "raw_text": "Verbal reasoning test. Measures ability to understand and evaluate written arguments and draw logical conclusions. For graduate and managerial level hiring.",
    },
    {
        "name": "Verify Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-inductive-reasoning-test/",
        "description": "Assesses ability to identify patterns and logical rules in abstract information. Ideal for technical, analytical, and problem-solving roles.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in multiple languages"],
        "raw_text": "Inductive reasoning test. Pattern recognition, abstract reasoning, problem solving. Good for technical and analytical roles. Graduate and professional level.",
    },
    {
        "name": "Verify Deductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-deductive-reasoning-test/",
        "description": "Measures ability to draw logical conclusions from a set of rules or premises. Suitable for roles requiring structured thinking.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in multiple languages"],
        "raw_text": "Deductive reasoning test. Logical thinking, rule application, structured problem solving. Graduate and managerial hiring.",
    },
    {
        "name": "Verify G+ Cognitive Ability",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-g-cognitive-ability/",
        "description": "Adaptive cognitive ability test covering numerical, verbal, and inductive reasoning. Provides a single general cognitive score with adaptive branching.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Manager", "Professional", "Director"],
        "duration": "36 minutes",
        "remote_testing": True,
        "adaptive": True,
        "languages": ["Available in 40+ languages"],
        "raw_text": "General cognitive ability. Adaptive test. Numerical, verbal, inductive reasoning combined. Single g-score. Used across all professional levels.",
    },
    {
        "name": "Numerical Reasoning - Interactive",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/numerical-reasoning-interactive/",
        "description": "Interactive numerical reasoning test in a work-simulated context with charts and data tables.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Professional"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Numerical reasoning interactive format. Work simulation. Data analysis, charts, tables.",
    },
    {
        "name": "Mechanical Comprehension",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mechanical-comprehension/",
        "description": "Assesses understanding of mechanical and physical concepts. Ideal for engineering, technical, and trade roles.",
        "test_types": ["A"],
        "job_levels": ["Operator", "Professional"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Mechanical comprehension. Engineering principles, physical concepts, mechanical aptitude. For technical, engineering, and trade roles.",
    },
    {
        "name": "Spatial Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/spatial-reasoning/",
        "description": "Measures ability to mentally manipulate and visualize 2D and 3D shapes. Useful for engineering, architecture, and design roles.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Professional"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Spatial reasoning. 2D and 3D visualization. For engineering, design, and technical roles.",
    },

    # ── KNOWLEDGE & SKILLS ───────────────────────────────────────────
    {
        "name": "Java 8 (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/java-8-new/",
        "description": "Tests knowledge of Java 8 programming language features, OOP concepts, collections, streams, and best practices.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Graduate"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Java 8 programming. Object-oriented programming, OOP, streams, lambda, collections, Spring, backend development, software engineering.",
    },
    {
        "name": "Core Java (Advanced Level)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/core-java-advanced-level-new/",
        "description": "Advanced Java programming assessment covering multithreading, design patterns, JVM, and enterprise concepts.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Senior"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Advanced Java. Senior developer. Multithreading, concurrency, JVM internals, design patterns, enterprise Java, Spring Boot.",
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/python-new/",
        "description": "Assesses Python programming skills including syntax, data structures, OOP, and common libraries.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Graduate"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Python programming. Data structures, OOP, libraries, scripting, automation, data science, backend. Software developer.",
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/javascript-new/",
        "description": "Tests JavaScript knowledge including ES6+, async programming, DOM manipulation, and common frameworks.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Graduate"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "JavaScript. ES6, async, DOM, frontend development, Node.js, React, web development.",
    },
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sql-new/",
        "description": "Evaluates SQL knowledge including queries, joins, aggregations, and database design.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Graduate"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "SQL. Database queries, joins, aggregations, subqueries, database design, data analyst, data engineer.",
    },
    {
        "name": ".NET (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/net-new/",
        "description": "Assesses .NET framework knowledge including C#, ASP.NET, and Microsoft development stack.",
        "test_types": ["K"],
        "job_levels": ["Professional"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": ".NET framework. C#, ASP.NET, Microsoft, backend, enterprise software development.",
    },
    {
        "name": "C++ (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cpp-new/",
        "description": "Tests C++ programming knowledge including memory management, STL, templates, and systems programming.",
        "test_types": ["K"],
        "job_levels": ["Professional"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "C++ programming. Memory management, pointers, STL, systems programming, embedded, game development.",
    },
    {
        "name": "Automata - Fix the Code",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-fix-the-code/",
        "description": "Coding simulation where candidates fix broken code. Tests practical debugging and programming skills in multiple languages.",
        "test_types": ["K", "S"],
        "job_levels": ["Professional", "Graduate"],
        "duration": "45 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Coding simulation. Debugging. Fix code. Practical programming. Software developer assessment. Multiple languages supported.",
    },
    {
        "name": "Automata Pro",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automata-pro/",
        "description": "Advanced coding simulation for software engineers. Candidates write working code from scratch to solve programming challenges.",
        "test_types": ["K", "S"],
        "job_levels": ["Professional", "Senior"],
        "duration": "60 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Advanced coding simulation. Write code from scratch. Software engineer. Algorithm, data structures, problem solving. Senior developer.",
    },
    {
        "name": "Technology Professional 8.0 - Short Form",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/technology-professional-8-0-short-form/",
        "description": "Assesses general technology knowledge, problem-solving, and professional skills for IT professionals.",
        "test_types": ["K", "A"],
        "job_levels": ["Professional"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Technology professional. IT knowledge. Problem solving. General tech. IT professional roles.",
    },
    {
        "name": "Microsoft Word (Office 2019)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/microsoft-word-office-2019/",
        "description": "Practical skills test for Microsoft Word 2019 including formatting, mail merge, and document management.",
        "test_types": ["K"],
        "job_levels": ["Clerical", "Administrative"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Microsoft Word. Office skills. Administrative. Clerical. Document formatting.",
    },
    {
        "name": "Microsoft Excel (Office 2019)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-office-2019/",
        "description": "Tests practical Excel skills including formulas, pivot tables, data analysis, and spreadsheet management.",
        "test_types": ["K"],
        "job_levels": ["Clerical", "Administrative", "Professional"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Microsoft Excel. Spreadsheet. Formulas, pivot tables, data analysis. Administrative, finance, analyst roles.",
    },

    # ── PERSONALITY & BEHAVIOUR ──────────────────────────────────────
    {
        "name": "OPQ32r",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32r/",
        "description": "Occupational Personality Questionnaire. Measures 32 personality characteristics relevant to workplace behaviour and performance. Gold standard for managerial and professional hiring.",
        "test_types": ["P"],
        "job_levels": ["Graduate", "Manager", "Director", "Professional"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in 30+ languages"],
        "raw_text": "OPQ32r. Occupational Personality Questionnaire. 32 traits. Workplace behaviour, leadership, teamwork, communication, influence, adaptability. For professional and managerial hiring. Personality assessment.",
    },
    {
        "name": "OPQ32 (n)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32-n/",
        "description": "Normative version of the OPQ32 personality questionnaire. Measures personality traits in relation to a comparison group.",
        "test_types": ["P"],
        "job_levels": ["Graduate", "Manager", "Professional"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in 30+ languages"],
        "raw_text": "OPQ32 normative personality questionnaire. Personality traits compared to norm group. Professional hiring.",
    },
    {
        "name": "Motivation Questionnaire MQM5",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/motivation-questionnaire-mqm5/",
        "description": "Measures 18 motivational factors that energize and direct an individual's behaviour at work. Helps understand what drives performance and engagement.",
        "test_types": ["M"],
        "job_levels": ["Manager", "Professional", "Graduate"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in multiple languages"],
        "raw_text": "Motivation questionnaire. MQ. 18 motivators. Work engagement, drive, what motivates employees. For professional and managerial selection and development.",
    },
    {
        "name": "Universal Competency Framework (UCF)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/universal-competency-framework/",
        "description": "Framework-based assessment mapping personality and behaviour to 8 competency factors and 20 competencies for the workplace.",
        "test_types": ["C", "P"],
        "job_levels": ["Manager", "Professional", "Graduate"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in multiple languages"],
        "raw_text": "UCF competency framework. 8 competency factors. Leadership, teamwork, results, adaptability. Competency-based selection.",
    },

    # ── SITUATIONAL JUDGEMENT ─────────────────────────────────────────
    {
        "name": "Situational Judgement Test - Manager",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/situational-judgement-test-manager/",
        "description": "Presents realistic managerial scenarios and assesses judgment in people management, decision-making, and leadership situations.",
        "test_types": ["B"],
        "job_levels": ["Manager"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Situational judgement test for managers. SJT. Managerial scenarios, people management, leadership, decision making.",
    },
    {
        "name": "Situational Judgement Test - Customer Service",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/situational-judgement-test-customer-service/",
        "description": "Assesses judgment in customer service scenarios including handling complaints, escalation, and service recovery.",
        "test_types": ["B"],
        "job_levels": ["Frontline", "Entry"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Situational judgement test customer service. SJT. Customer facing roles, complaint handling, service skills.",
    },
    {
        "name": "Situational Judgement Test - Graduate",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/situational-judgement-test-graduate/",
        "description": "Designed for graduate-level roles. Assesses judgment in early-career professional scenarios.",
        "test_types": ["B"],
        "job_levels": ["Graduate", "Entry"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Graduate situational judgement test. SJT. Entry level, early career professional scenarios.",
    },

    # ── SIMULATIONS & EXERCISES ───────────────────────────────────────
    {
        "name": "MFS - Inbox Simulation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mfs-inbox-simulation/",
        "description": "Email inbox simulation exercise. Candidates prioritize and respond to a series of work emails. Assesses organizational skills, judgment, and communication.",
        "test_types": ["E", "S"],
        "job_levels": ["Manager", "Professional"],
        "duration": "40 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Inbox simulation. Email management. Manager assessment centre. Prioritization, decision making, written communication.",
    },
    {
        "name": "Smart Interview Now",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/smart-interview-now/",
        "description": "AI-powered structured video interview solution. Candidates record video responses to competency-based questions.",
        "test_types": ["E"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["Available in multiple languages"],
        "raw_text": "Video interview. Structured interview. Competency based. AI scoring. Remote interview.",
    },

    # ── BEHAVIOURAL / COMPETENCY ──────────────────────────────────────
    {
        "name": "Graduate 8.0 Short Form",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/graduate-8-0-short-form/",
        "description": "Short-form cognitive battery designed for graduate-level selection. Covers verbal, numerical, and inductive reasoning.",
        "test_types": ["A"],
        "job_levels": ["Graduate"],
        "duration": "36 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Graduate assessment. Cognitive battery. Verbal, numerical, inductive reasoning. Short form. Graduate recruitment.",
    },
    {
        "name": "Managerial & Professional Short Form 8.0",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/managerial-professional-short-form-8-0/",
        "description": "Cognitive ability battery for managerial and professional level selection. Measures reasoning abilities relevant to complex decision-making.",
        "test_types": ["A"],
        "job_levels": ["Manager", "Professional"],
        "duration": "36 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Managerial professional cognitive assessment. Reasoning. Complex decisions. Manager hiring.",
    },
    {
        "name": "Customer Contact Styles Questionnaire",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/customer-contact-styles-questionnaire/",
        "description": "Personality questionnaire designed for customer-facing and contact centre roles. Assesses service orientation, resilience, and interpersonal style.",
        "test_types": ["P"],
        "job_levels": ["Frontline", "Entry"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Customer contact personality. Service orientation. Call centre. Customer service. Resilience, interpersonal style, frontline roles.",
    },
    {
        "name": "Sales Styles Questionnaire",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-styles-questionnaire/",
        "description": "Personality questionnaire tailored for sales roles. Measures drive, persuasiveness, and relationship-building relevant to sales performance.",
        "test_types": ["P"],
        "job_levels": ["Professional", "Manager"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Sales personality questionnaire. Drive, persuasion, relationship building, commercial awareness. For sales roles and account management.",
    },
    {
        "name": "Remote Worker Personality Questionnaire",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/remote-worker-personality-questionnaire/",
        "description": "Assesses personality traits associated with effectiveness in remote and hybrid work environments including self-management and digital communication.",
        "test_types": ["P"],
        "job_levels": ["Professional", "Manager", "Graduate"],
        "duration": "20 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Remote worker personality. Work from home. Hybrid working. Self-management. Digital communication. Remote team.",
    },
    {
        "name": "Workplace English (Business Writing)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/workplace-english-business-writing/",
        "description": "Tests written English communication skills in a business context including email writing, grammar, and clarity.",
        "test_types": ["K"],
        "job_levels": ["Professional", "Clerical"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "English writing. Business communication. Email, grammar, clarity, written communication skills.",
    },
    {
        "name": "Occupational Safety (Safety 7.1)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/occupational-safety-safety-7-1/",
        "description": "Measures safety attitudes, risk awareness, and safety behaviours relevant to industrial and operational roles.",
        "test_types": ["P", "K"],
        "job_levels": ["Operator", "Frontline"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Safety assessment. Occupational safety. Risk awareness. Industrial safety. Frontline worker. Operator.",
    },
    {
        "name": "Dependability & Safety Instrument (DSI)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/dependability-safety-instrument/",
        "description": "Short personality measure focused on dependability, reliability, and counterproductive work behaviour for frontline and operational roles.",
        "test_types": ["P"],
        "job_levels": ["Operator", "Frontline", "Entry"],
        "duration": "15 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Dependability, reliability. Counterproductive behaviour. Integrity. Frontline, operational, entry level roles.",
    },
    {
        "name": "Cognitive Ability Test (CAT4)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cognitive-ability-test/",
        "description": "Multi-battery cognitive ability assessment covering reasoning, processing speed, and working memory. Suitable for volume hiring.",
        "test_types": ["A"],
        "job_levels": ["Entry", "Frontline", "Graduate"],
        "duration": "30 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "Cognitive ability test. Reasoning, processing speed, working memory. Volume hiring. Entry level, frontline.",
    },
    {
        "name": "General Ability Test (GAT)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/general-ability-test/",
        "description": "Measures general cognitive ability for graduate and professional roles. Covers verbal, numerical, and abstract reasoning.",
        "test_types": ["A"],
        "job_levels": ["Graduate", "Professional"],
        "duration": "25 minutes",
        "remote_testing": True,
        "adaptive": False,
        "languages": ["English"],
        "raw_text": "General ability test. Cognitive ability. Verbal, numerical, abstract reasoning. Graduate, professional level.",
    },
]


def build_seed_catalog():
    out_path = "data/catalog.json"
    with open(out_path, "w") as f:
        json.dump(SEED_CATALOG, f, indent=2)
    print(f"Wrote {len(SEED_CATALOG)} seed products to {out_path}")

    # Print summary
    from collections import Counter
    type_counts = Counter(t for p in SEED_CATALOG for t in p["test_types"])
    print("\nBreakdown by test type:")
    type_names = {"A": "Ability", "K": "Knowledge", "P": "Personality", "B": "SJT", "M": "Motivation", "C": "Competency", "E": "Exercise", "S": "Simulation"}
    for t, count in sorted(type_counts.items()):
        print(f"  {t} ({type_names.get(t, t)}): {count}")


if __name__ == "__main__":
    import os
    os.makedirs("data", exist_ok=True)
    build_seed_catalog()